name: build application

on: 
  push:
    branches:
    - 'app'

jobs:

  build-springboot:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
            
        - name: Build with maven
          run: |
            ls -la
            mvn clean install



